apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-i00017
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/RedwanAlkurdi/argocd-applicationset-example.git
        revision: main
        files:
          - path: deployment/I00017/**/config.json
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        targetRevision: 18.2.0
        helm:
          valuesObject:
            fullnameOverride: '{{name}}'
            replicaCount: {{replicaCount}}
            image:
              repository: '{{image_repository}}'
              tag: '{{image_tag}}'
            service:
              type: '{{service_type}}'
              ports:
                http: {{service_port}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
